logging:
  level: 
    root: debug

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 2m
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5s
        # 连接池中的最小空闲连接
        min-idle: 1
  sql:
    init:
      schema-locations:
        - classpath:db/chen_tables_h2.sql
        - classpath:db/quartz_tables_h2.sql

  shardingsphere:
    enabled: true
    datasource:
      names: master
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=true
        username: sa
        password:
        initialSize: 5
        maxActive: 10
        minIdle: 3
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 50
        connectionPropertise:
        #这么配置是默认的过滤器
        #filters: stat,wall,slf4j,config,

    sharding:
      default-data-source-name: master

    props:
      sql:
        show: true

