server:
  port: 8080

  error:
    path: /error
    includeException: true
    includeStacktrace: ALWAYS

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: chen-f-template
  main:
    banner-mode: console

  mvc:
    date-format: yyyyMMddhhmmss
    #抛出404异常,默认不抛出404异常,会转发到/error
    throw-exception-if-no-handler-found: false
    locale: zh_CN

  resources:
    #是否使用默认资源映射
    add-mappings: true

  messages:
    basename: org/springframework/security/messages,i18n/messages

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  session:
    store-type: redis
    timeout: 60m

  cache:
    type: redis
    redis:
      time-to-live: 24h
      cache-null-values: true
      key-prefix: cache

  quartz:
    scheduler-name: quartz
    auto-startup: true
    startup-delay: 0s
    wait-for-jobs-to-complete-on-shutdown: true
    overwrite-existing-jobs: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceName: quartz
      #集群中每个实例都要唯一
      org.quartz.scheduler.instanceId: AUTO
      #是否调过版本更新检查
      org.quartz.scheduler.skipUpdateCheck: true
      org.quartz.scheduler.jobFactory.class: org.springframework.scheduling.quartz.SpringBeanJobFactory
      #线程
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 20
      org.quartz.threadPool.threadPriority: 5
      org.quartz.scheduler.threadName: quartz
      org.quartz.threadPool.threadNamePrefix: quartz
      #线程继承初始化线程的上下文类加载器
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      #Cluster开启集群
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      #数据库方言
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.tablePrefix: QRTZ_
      #调度实例失效的检查时间间隔
      org.quartz.jobStore.clusterCheckinInterval: 200000
      org.quartz.jobStore.dontSetAutoCommitFalse: false
      org.quartz.jobStore.selectWithLockSQL: SELECT * FROM {0}LOCKS WHERE LOCK_NAME = ? FOR UPDATE
      org.quartz.jobStore.txIsolationLevelSerializable: false
      org.quartz.jobStore.acquireTriggersWithinLock: false
      org.quartz.scheduler.batchTriggerAcquisitionMaxCount: 50
